ALTER TABLE SPRING_SESSION_ATTRIBUTES
    DROP FOREIGN KEY SPRING_SESSION_ATTRIBUTES_FK;

DROP TABLE SPRING_SESSION;

DROP TABLE SPRING_SESSION_ATTRIBUTES;

ALTER TABLE document
    DROP COLUMN code;
