version: '3.9'

services:
  db:
    image: mysql
    networks:
      - doky-dev-net
    restart: unless-stopped
    command: '--default-authentication-plugin=mysql_native_password'
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: doky-dev
      MYSQL_USER: doky-dev
      MYSQL_PASSWORD: doky-dev
      MYSQL_TCP_PORT: 3310

  server:
    depends_on:
      db:
        condition: service_started
    build:
      context: .
      args:
        JAR_FILE: server.jar
    networks:
      - doky-dev-net
    ports:
      - 8118:8118
    environment:
      ENV_PROFILE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3310/doky-dev?autoreconnect=true
      SPRING_DATASOURCE_USERNAME: doky-dev
      SPRING_DATASOURCE_PASSWORD: doky-dev

networks:
  doky-dev-net:
