name: documentation

on:
    push:
      branches: [ "main" ]

jobs:

  publish-javadoc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      - name: Generate documentation with Gradle Wrapper
        working-directory: server
        run: ./gradlew dokkaHtml
      - name: Deploy JavaDoc 🚀
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: javadoc
          clean: true
          folder: server/build/dokka/html
          target-folder: javadoc
